# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sophos.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'sophos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csophos.proto\x12\x06sophos\"a\n\x10UploadDocRequest\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\x0c\x12\n\n\x02iv\x18\x02 \x01(\x0c\x12\x12\n\nciphertext\x18\x03 \x01(\x0c\x12\x0b\n\x03tag\x18\x04 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x05 \x01(\t\"(\n\nIndexEntry\x12\n\n\x02ut\x18\x01 \x01(\x0c\x12\x0e\n\x06\x65nc_id\x18\x02 \x01(\x0c\"9\n\x12UploadIndexRequest\x12#\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x12.sophos.IndexEntry\"b\n\rSearchRequest\x12\x10\n\x08kw_bytes\x18\x01 \x01(\x0c\x12\x10\n\x08st_bytes\x18\x02 \x01(\x0c\x12\x0f\n\x07\x63ounter\x18\x03 \x01(\x05\x12\r\n\x05rsa_e\x18\x04 \x01(\x0c\x12\r\n\x05rsa_n\x18\x05 \x01(\x0c\",\n\x0cSearchResult\x12\x0e\n\x06\x65nc_id\x18\x01 \x01(\x0c\x12\x0c\n\x04step\x18\x02 \x01(\x05\"!\n\x0f\x46\x65tchDocRequest\x12\x0e\n\x06\x64oc_id\x18\x01 \x01(\x0c\"M\n\x0c\x45ncryptedDoc\x12\n\n\x02iv\x18\x01 \x01(\x0c\x12\x12\n\nciphertext\x18\x02 \x01(\x0c\x12\x0b\n\x03tag\x18\x03 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x04 \x01(\t\"\r\n\x0b\x44umpRequest\"\x0e\n\x0cResetRequest\"\r\n\x0bPingRequest\"\x1e\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t2\x8e\x03\n\x0cSophosServer\x12\x37\n\x0eUploadDocument\x12\x18.sophos.UploadDocRequest\x1a\x0b.sophos.Ack\x12\x36\n\x0bUploadIndex\x12\x1a.sophos.UploadIndexRequest\x1a\x0b.sophos.Ack\x12\x37\n\x06Search\x12\x15.sophos.SearchRequest\x1a\x14.sophos.SearchResult0\x01\x12>\n\rFetchDocument\x12\x17.sophos.FetchDocRequest\x1a\x14.sophos.EncryptedDoc\x12\x36\n\tDumpIndex\x12\x13.sophos.DumpRequest\x1a\x12.sophos.IndexEntry0\x01\x12\x32\n\rResetDatabase\x12\x14.sophos.ResetRequest\x1a\x0b.sophos.Ack\x12(\n\x04Ping\x12\x13.sophos.PingRequest\x1a\x0b.sophos.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sophos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADDOCREQUEST']._serialized_start=24
  _globals['_UPLOADDOCREQUEST']._serialized_end=121
  _globals['_INDEXENTRY']._serialized_start=123
  _globals['_INDEXENTRY']._serialized_end=163
  _globals['_UPLOADINDEXREQUEST']._serialized_start=165
  _globals['_UPLOADINDEXREQUEST']._serialized_end=222
  _globals['_SEARCHREQUEST']._serialized_start=224
  _globals['_SEARCHREQUEST']._serialized_end=322
  _globals['_SEARCHRESULT']._serialized_start=324
  _globals['_SEARCHRESULT']._serialized_end=368
  _globals['_FETCHDOCREQUEST']._serialized_start=370
  _globals['_FETCHDOCREQUEST']._serialized_end=403
  _globals['_ENCRYPTEDDOC']._serialized_start=405
  _globals['_ENCRYPTEDDOC']._serialized_end=482
  _globals['_DUMPREQUEST']._serialized_start=484
  _globals['_DUMPREQUEST']._serialized_end=497
  _globals['_RESETREQUEST']._serialized_start=499
  _globals['_RESETREQUEST']._serialized_end=513
  _globals['_PINGREQUEST']._serialized_start=515
  _globals['_PINGREQUEST']._serialized_end=528
  _globals['_ACK']._serialized_start=530
  _globals['_ACK']._serialized_end=560
  _globals['_SOPHOSSERVER']._serialized_start=563
  _globals['_SOPHOSSERVER']._serialized_end=961
# @@protoc_insertion_point(module_scope)
