# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sophos_pb2 as sophos__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sophos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SophosServerStub:
    """─────────────────────────────────────────────────────────────────────────────
    SOPHOS SSE gRPC Service
    Forward-Private Symmetric Searchable Encryption (Bost, CCS 2016)
    ─────────────────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadDocument = channel.unary_unary(
                '/sophos.SophosServer/UploadDocument',
                request_serializer=sophos__pb2.UploadDocRequest.SerializeToString,
                response_deserializer=sophos__pb2.Ack.FromString,
                _registered_method=True)
        self.UploadIndex = channel.unary_unary(
                '/sophos.SophosServer/UploadIndex',
                request_serializer=sophos__pb2.UploadIndexRequest.SerializeToString,
                response_deserializer=sophos__pb2.Ack.FromString,
                _registered_method=True)
        self.Search = channel.unary_stream(
                '/sophos.SophosServer/Search',
                request_serializer=sophos__pb2.SearchRequest.SerializeToString,
                response_deserializer=sophos__pb2.SearchResult.FromString,
                _registered_method=True)
        self.FetchDocument = channel.unary_unary(
                '/sophos.SophosServer/FetchDocument',
                request_serializer=sophos__pb2.FetchDocRequest.SerializeToString,
                response_deserializer=sophos__pb2.EncryptedDoc.FromString,
                _registered_method=True)
        self.DumpIndex = channel.unary_stream(
                '/sophos.SophosServer/DumpIndex',
                request_serializer=sophos__pb2.DumpRequest.SerializeToString,
                response_deserializer=sophos__pb2.IndexEntry.FromString,
                _registered_method=True)
        self.ResetDatabase = channel.unary_unary(
                '/sophos.SophosServer/ResetDatabase',
                request_serializer=sophos__pb2.ResetRequest.SerializeToString,
                response_deserializer=sophos__pb2.Ack.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/sophos.SophosServer/Ping',
                request_serializer=sophos__pb2.PingRequest.SerializeToString,
                response_deserializer=sophos__pb2.Ack.FromString,
                _registered_method=True)


class SophosServerServicer:
    """─────────────────────────────────────────────────────────────────────────────
    SOPHOS SSE gRPC Service
    Forward-Private Symmetric Searchable Encryption (Bost, CCS 2016)
    ─────────────────────────────────────────────────────────────────────────────

    """

    def UploadDocument(self, request, context):
        """Store an encrypted document blob on the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadIndex(self, request, context):
        """Store a batch of encrypted index entries (UT → EncID)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search: server walks the RSA trapdoor chain and streams back encrypted doc IDs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchDocument(self, request, context):
        """Retrieve an encrypted document by its doc_id
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DumpIndex(self, request, context):
        """Dump index entries for the Server State panel (demo/debug)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetDatabase(self, request, context):
        """Reset / clear all index entries and document store
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check + stats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SophosServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDocument,
                    request_deserializer=sophos__pb2.UploadDocRequest.FromString,
                    response_serializer=sophos__pb2.Ack.SerializeToString,
            ),
            'UploadIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadIndex,
                    request_deserializer=sophos__pb2.UploadIndexRequest.FromString,
                    response_serializer=sophos__pb2.Ack.SerializeToString,
            ),
            'Search': grpc.unary_stream_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=sophos__pb2.SearchRequest.FromString,
                    response_serializer=sophos__pb2.SearchResult.SerializeToString,
            ),
            'FetchDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchDocument,
                    request_deserializer=sophos__pb2.FetchDocRequest.FromString,
                    response_serializer=sophos__pb2.EncryptedDoc.SerializeToString,
            ),
            'DumpIndex': grpc.unary_stream_rpc_method_handler(
                    servicer.DumpIndex,
                    request_deserializer=sophos__pb2.DumpRequest.FromString,
                    response_serializer=sophos__pb2.IndexEntry.SerializeToString,
            ),
            'ResetDatabase': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetDatabase,
                    request_deserializer=sophos__pb2.ResetRequest.FromString,
                    response_serializer=sophos__pb2.Ack.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=sophos__pb2.PingRequest.FromString,
                    response_serializer=sophos__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sophos.SophosServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sophos.SophosServer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SophosServer:
    """─────────────────────────────────────────────────────────────────────────────
    SOPHOS SSE gRPC Service
    Forward-Private Symmetric Searchable Encryption (Bost, CCS 2016)
    ─────────────────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def UploadDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sophos.SophosServer/UploadDocument',
            sophos__pb2.UploadDocRequest.SerializeToString,
            sophos__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sophos.SophosServer/UploadIndex',
            sophos__pb2.UploadIndexRequest.SerializeToString,
            sophos__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sophos.SophosServer/Search',
            sophos__pb2.SearchRequest.SerializeToString,
            sophos__pb2.SearchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sophos.SophosServer/FetchDocument',
            sophos__pb2.FetchDocRequest.SerializeToString,
            sophos__pb2.EncryptedDoc.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DumpIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sophos.SophosServer/DumpIndex',
            sophos__pb2.DumpRequest.SerializeToString,
            sophos__pb2.IndexEntry.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetDatabase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sophos.SophosServer/ResetDatabase',
            sophos__pb2.ResetRequest.SerializeToString,
            sophos__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sophos.SophosServer/Ping',
            sophos__pb2.PingRequest.SerializeToString,
            sophos__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
